apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drive-service.fullname" . }}
  labels:
      {{ include "drive-service.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{ include "drive-service.selectorLabels" . }}
  template:
    metadata:
      labels:
        {{ include "drive-service.selectorLabels" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DATA_PLATFORM_DRIVE_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "drive-service.fullname" . }}
                  key: dataPlatformDrivePath
            - name: DATA_PLATFORM_FILE_MAX_SIZE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "drive-service.fullname" . }}
                  key: dataPlatformFileMaxSize
            - name: SPRING_APPLICATION_JSON
              value: |
                {"data.platform.drive.path":"{{ .Values.env.DATA_PLATFORM_DRIVE_PATH }}","data.platform.file.max.size":{{ .Values.env.DATA_PLATFORM_FILE_MAX_SIZE }}}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        kubernetes.io/os: {{ .Values.kubernetes.os }}